package:
    name: pandas
    version: 0.18.1

build:
    number: {{environ.get('APPVEYOR_BUILD_NUMBER', 0)}}  # [win]
    string: np{{ environ.get('CONDA_NPY') }}py{{ environ.get('CONDA_PY') }}_{{ environ.get('APPVEYOR_BUILD_NUMBER', 0) }} # [win]

source:

    # conda-build needs a full clone
    # rather than a shallow git_url type clone
    # https://github.com/conda/conda-build/issues/780
    path: ../../

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - pytz
    - python-dateutil

  run:
    - python
    - numpy x.x
    - python-dateutil
    - pytz

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD
