package: pandas
user: jreback

install:
  - conda config --add channels pandas

before_script:
  - python -V

platform:
  - linux-64
  #- linux-32
  - osx-64
  #- win-32
  - win-64
engine:
  - python=2.7
  - python=3.4
script:
  - conda build conda.recipe --quiet

iotimeout: 600

build_targets: conda

notifications:
  email:
    recipients: ['jeff@reback.net']
