
language: python

env:

  global:
  # scatterci API key
  #- secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
  # ironcache API key
  - secure: "e4eEFn9nDQc3Xa5BWYkzfX37jaWVq89XidVX+rcCNEr5OlOImvveeXnF1IzbRXznH4Sv0YsLwUd8RGUWOmyCvkONq/VJeqCHWtTMyfaCIdqSyhIP9Odz8r9ahch+Y0XFepBey92AJHmlnTh+2GjCDgIiqq4fzglojnp56Vg1ojA="
  - secure: "CjmYmY5qEu3KrvMtel6zWFEtMq8ORBeS1S1odJHnjQpbwT1KY2YFZRVlLphfyDQXSz6svKUdeRrCNp65baBzs3DQNA8lIuXGIBYFeJxqVGtYAZZs6+TzBPfJJK798sGOj5RshrOJkFG2rdlWNuTq/XphI0JOrN3nPUkRrdQRpAw="
  # pandas-docs-bot GH
  - secure: "PCzUFR8CHmw9lH84p4ygnojdF7Z8U5h7YfY0RyT+5K/aiQ1ZTU3ZkDTPI0/rR5FVMxsEEKEQKMcc5fvqW0PeD7Q2wRmluloKgT9w4EVEJ1ppKf7lITPcvZR2QgVOvjv4AfDtibLHFNiaSjzoqyJVjM4igjOu8WTlF3JfZcmOQjQ="

git:
    # for cloning
    depth: 300

matrix:
    fast_finish: true
    include:
    - language: objective-c
      os: osx
      compiler: clang
      osx_image: xcode6.4
      env:
        - JOB_NAME: "35_osx"
        - NOSE_ARGS="not slow and not network and not disabled"
        - BUILD_TYPE=conda
        - JOB_TAG=_OSX
        - TRAVIS_PYTHON_VERSION=3.5
    - python: 2.7
      env:
      - JOB_NAME: "27_slow_nnet_LOCALE"
      - NOSE_ARGS="slow and not network and not disabled"
      - LOCALE_OVERRIDE="zh_CN.GB18030"
      - FULL_DEPS=true
      - JOB_TAG=_LOCALE
    - python: 2.7
      env:
      - JOB_NAME: "27_nslow"
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - LINT=true
    - python: 3.4
      env:
      - JOB_NAME: "34_nslow"
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
    - python: 3.5
      env:
      - JOB_NAME: "35_nslow"
      - NOSE_ARGS="not slow and not network and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
      - COVERAGE=true
    - python: 2.7
      env:
      - JOB_NAME: "27_slow"
      - JOB_TAG=_SLOW
      - NOSE_ARGS="slow and not network and not disabled"
      - FULL_DEPS=true
    - python: 3.4
      env:
      - JOB_NAME: "34_slow"
      - JOB_TAG=_SLOW
      - NOSE_ARGS="slow and not network and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
    - python: 2.7
      env:
      - JOB_NAME: "27_build_test_conda"
      - JOB_TAG=_BUILD_TEST
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - BUILD_TEST=true
    - python: 3.5
      env:
      - JOB_NAME: "35_numpy_dev"
      - JOB_TAG=_NUMPY_DEV
      - NOSE_ARGS="not slow and not network and not disabled"
      - PANDAS_TESTING_MODE="deprecate"
    - python: 2.7
      env:
      - JOB_NAME: "27_nslow_nnet_COMPAT"
      - NOSE_ARGS="not slow and not network and not disabled"
      - LOCALE_OVERRIDE="it_IT.UTF-8"
      - INSTALL_TEST=true
      - JOB_TAG=_COMPAT
    - python: 2.7
      env:
      - JOB_NAME: "doc_build"
      - FULL_DEPS=true
      - DOC_BUILD=true # if rst files were changed, build docs in parallel with tests
      - JOB_TAG=_DOC_BUILD
    allow_failures:
      - python: 2.7
        env:
        - JOB_NAME: "27_slow"
        - JOB_TAG=_SLOW
        - NOSE_ARGS="slow and not network and not disabled"
        - FULL_DEPS=true
      - python: 3.4
        env:
        - JOB_NAME: "34_slow"
        - JOB_TAG=_SLOW
        - NOSE_ARGS="slow and not network and not disabled"
        - FULL_DEPS=true
        - CLIPBOARD=xsel
      - python: 2.7
        env:
        - JOB_NAME: "27_build_test_conda"
        - JOB_TAG=_BUILD_TEST
        - NOSE_ARGS="not slow and not disabled"
        - FULL_DEPS=true
        - BUILD_TEST=true
      - python: 3.5
        env:
        - JOB_NAME: "35_numpy_dev"
        - JOB_TAG=_NUMPY_DEV
        - NOSE_ARGS="not slow and not network and not disabled"
        - PANDAS_TESTING_MODE="deprecate"
      - python: 2.7
        env:
        - JOB_NAME: "27_nslow_nnet_COMPAT"
        - NOSE_ARGS="not slow and not network and not disabled"
        - LOCALE_OVERRIDE="it_IT.UTF-8"
        - INSTALL_TEST=true
        - JOB_TAG=_COMPAT
      - python: 2.7
        env:
        - JOB_NAME: "doc_build"
        - FULL_DEPS=true
        - DOC_BUILD=true
        - JOB_TAG=_DOC_BUILD

before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - export PATH="$HOME/miniconda/bin:$PATH"
  - df -h
  - date
  - pwd
  - uname -a
  - python -V
# git info & get tags
  - git --version
  - git tag
  - ci/before_install_travis.sh
  - export DISPLAY=:99.0

install:
  - echo "install"
  - ci/prep_ccache.sh
  - ci/install_travis.sh
  - ci/submit_ccache.sh

before_script:
  - source activate pandas && pip install codecov
  - ci/install_db.sh

script:
  - echo "script"
  - ci/run_build_docs.sh
  - ci/script.sh
  - ci/lint.sh

after_success:
  - source activate pandas && codecov

after_script:
  - ci/install_test.sh
  - source activate pandas && ci/print_versions.py
  - ci/print_skipped.py /tmp/nosetests.xml
